// utils/validators.ts

export interface CountryCode {
  name: string;
  code: string;
  iso: string;
  minLength: number;
  maxLength: number;
}

// Paste your full 200-country array here
export const countryCodes: CountryCode[] = [
  { "name": "Afghanistan", "code": "+93", "iso": "AF", "minLength": 9, "maxLength": 9 },
  { "name": "Albania", "code": "+355", "iso": "AL", "minLength": 9, "maxLength": 9 },
  { "name": "Algeria", "code": "+213", "iso": "DZ", "minLength": 9, "maxLength": 9 },
  { "name": "Andorra", "code": "+376", "iso": "AD", "minLength": 6, "maxLength": 6 },
  { "name": "Angola", "code": "+244", "iso": "AO", "minLength": 9, "maxLength": 9 },
  { "name": "Antigua and Barbuda", "code": "+1-268", "iso": "AG", "minLength": 7, "maxLength": 7 },
  { "name": "Argentina", "code": "+54", "iso": "AR", "minLength": 10, "maxLength": 10 },
  { "name": "Armenia", "code": "+374", "iso": "AM", "minLength": 8, "maxLength": 8 },
  { "name": "Australia", "code": "+61", "iso": "AU", "minLength": 9, "maxLength": 9 },
  { "name": "Austria", "code": "+43", "iso": "AT", "minLength": 10, "maxLength": 10 },
  { "name": "Azerbaijan", "code": "+994", "iso": "AZ", "minLength": 9, "maxLength": 9 },
  { "name": "Bahamas", "code": "+1-242", "iso": "BS", "minLength": 7, "maxLength": 7 },
  { "name": "Bahrain", "code": "+973", "iso": "BH", "minLength": 8, "maxLength": 8 },
  { "name": "Bangladesh", "code": "+880", "iso": "BD", "minLength": 10, "maxLength": 10 },
  { "name": "Barbados", "code": "+1-246", "iso": "BB", "minLength": 7, "maxLength": 7 },
  { "name": "Belarus", "code": "+375", "iso": "BY", "minLength": 9, "maxLength": 9 },
  { "name": "Belgium", "code": "+32", "iso": "BE", "minLength": 9, "maxLength": 9 },
  { "name": "Belize", "code": "+501", "iso": "BZ", "minLength": 7, "maxLength": 7 },
  { "name": "Benin", "code": "+229", "iso": "BJ", "minLength": 8, "maxLength": 8 },
  { "name": "Bhutan", "code": "+975", "iso": "BT", "minLength": 8, "maxLength": 8 },
  { "name": "Bolivia", "code": "+591", "iso": "BO", "minLength": 8, "maxLength": 8 },
  { "name": "Bosnia and Herzegovina", "code": "+387", "iso": "BA", "minLength": 8, "maxLength": 8 },
  { "name": "Botswana", "code": "+267", "iso": "BW", "minLength": 7, "maxLength": 7 },
  { "name": "Brazil", "code": "+55", "iso": "BR", "minLength": 10, "maxLength": 11 },
  { "name": "Brunei", "code": "+673", "iso": "BN", "minLength": 7, "maxLength": 7 },
  { "name": "Bulgaria", "code": "+359", "iso": "BG", "minLength": 9, "maxLength": 9 },
  { "name": "Burkina Faso", "code": "+226", "iso": "BF", "minLength": 8, "maxLength": 8 },
  { "name": "Burundi", "code": "+257", "iso": "BI", "minLength": 8, "maxLength": 8 },
  { "name": "Cabo Verde", "code": "+238", "iso": "CV", "minLength": 7, "maxLength": 7 },
  { "name": "Cambodia", "code": "+855", "iso": "KH", "minLength": 8, "maxLength": 9 },
  { "name": "Cameroon", "code": "+237", "iso": "CM", "minLength": 8, "maxLength": 8 },
  { "name": "Canada", "code": "+1", "iso": "CA", "minLength": 10, "maxLength": 10 },
  { "name": "Central African Republic", "code": "+236", "iso": "CF", "minLength": 8, "maxLength": 8 },
  { "name": "Chad", "code": "+235", "iso": "TD", "minLength": 8, "maxLength": 8 },
  { "name": "Chile", "code": "+56", "iso": "CL", "minLength": 9, "maxLength": 9 },
  { "name": "China", "code": "+86", "iso": "CN", "minLength": 11, "maxLength": 11 },
  { "name": "Colombia", "code": "+57", "iso": "CO", "minLength": 10, "maxLength": 10 },
  { "name": "Comoros", "code": "+269", "iso": "KM", "minLength": 7, "maxLength": 7 },
  { "name": "Congo (Congo-Brazzaville)", "code": "+242", "iso": "CG", "minLength": 9, "maxLength": 9 },
  { "name": "Congo (Congo-Kinshasa)", "code": "+243", "iso": "CD", "minLength": 9, "maxLength": 9 },
  { "name": "Costa Rica", "code": "+506", "iso": "CR", "minLength": 8, "maxLength": 8 },
  { "name": "Croatia", "code": "+385", "iso": "HR", "minLength": 9, "maxLength": 9 },
  { "name": "Cuba", "code": "+53", "iso": "CU", "minLength": 8, "maxLength": 8 },
  { "name": "Cyprus", "code": "+357", "iso": "CY", "minLength": 8, "maxLength": 8 },
  { "name": "Czechia", "code": "+420", "iso": "CZ", "minLength": 9, "maxLength": 9 },
  { "name": "Denmark", "code": "+45", "iso": "DK", "minLength": 8, "maxLength": 8 },
  { "name": "Djibouti", "code": "+253", "iso": "DJ", "minLength": 8, "maxLength": 8 },
  { "name": "Dominica", "code": "+1-767", "iso": "DM", "minLength": 7, "maxLength": 7 },
  { "name": "Dominican Republic", "code": "+1-809", "iso": "DO", "minLength": 10, "maxLength": 10 },
  { "name": "Ecuador", "code": "+593", "iso": "EC", "minLength": 9, "maxLength": 9 },
  { "name": "Egypt", "code": "+20", "iso": "EG", "minLength": 9, "maxLength": 9 },
  { "name": "El Salvador", "code": "+503", "iso": "SV", "minLength": 8, "maxLength": 8 },
  { "name": "Equatorial Guinea", "code": "+240", "iso": "GQ", "minLength": 9, "maxLength": 9 },
  { "name": "Eritrea", "code": "+291", "iso": "ER", "minLength": 7, "maxLength": 7 },
  { "name": "Estonia", "code": "+372", "iso": "EE", "minLength": 8, "maxLength": 8 },
  { "name": "Eswatini", "code": "+268", "iso": "SZ", "minLength": 8, "maxLength": 8 },
  { "name": "Ethiopia", "code": "+251", "iso": "ET", "minLength": 9, "maxLength": 9 },
  { "name": "Fiji", "code": "+679", "iso": "FJ", "minLength": 7, "maxLength": 7 },
  { "name": "Finland", "code": "+358", "iso": "FI", "minLength": 9, "maxLength": 9 },
  { "name": "France", "code": "+33", "iso": "FR", "minLength": 9, "maxLength": 9 },
  { "name": "Gabon", "code": "+241", "iso": "GA", "minLength": 8, "maxLength": 8 },
  { "name": "Gambia", "code": "+220", "iso": "GM", "minLength": 7, "maxLength": 7 },
  { "name": "Georgia", "code": "+995", "iso": "GE", "minLength": 9, "maxLength": 9 },
  { "name": "Germany", "code": "+49", "iso": "DE", "minLength": 10, "maxLength": 11 },
  { "name": "Ghana", "code": "+233", "iso": "GH", "minLength": 9, "maxLength": 9 },
  { "name": "Greece", "code": "+30", "iso": "GR", "minLength": 10, "maxLength": 10 },
  { "name": "Grenada", "code": "+1-473", "iso": "GD", "minLength": 7, "maxLength": 7 },
  { "name": "Guatemala", "code": "+502", "iso": "GT", "minLength": 8, "maxLength": 8 },
  { "name": "Guinea", "code": "+224", "iso": "GN", "minLength": 8, "maxLength": 8 },
  { "name": "Guinea-Bissau", "code": "+245", "iso": "GW", "minLength": 8, "maxLength": 8 },
  { "name": "Guyana", "code": "+592", "iso": "GY", "minLength": 7, "maxLength": 7 },
  { "name": "Haiti", "code": "+509", "iso": "HT", "minLength": 8, "maxLength": 8 },
  { "name": "Honduras", "code": "+504", "iso": "HN", "minLength": 8, "maxLength": 8 },
  { "name": "Hungary", "code": "+36", "iso": "HU", "minLength": 9, "maxLength": 9 },
  { "name": "Iceland", "code": "+354", "iso": "IS", "minLength": 7, "maxLength": 7 },
  { "name": "India", "code": "+91", "iso": "IN", "minLength": 10, "maxLength": 10 },
  { "name": "Indonesia", "code": "+62", "iso": "ID", "minLength": 10, "maxLength": 12 },
  { "name": "Iran", "code": "+98", "iso": "IR", "minLength": 10, "maxLength": 10 },
  { "name": "Iraq", "code": "+964", "iso": "IQ", "minLength": 10, "maxLength": 10 },
  { "name": "Ireland", "code": "+353", "iso": "IE", "minLength": 9, "maxLength": 9 },
  { "name": "Israel", "code": "+972", "iso": "IL", "minLength": 9, "maxLength": 9 },
  { "name": "Italy", "code": "+39", "iso": "IT", "minLength": 10, "maxLength": 10 },
  { "name": "Jamaica", "code": "+1-876", "iso": "JM", "minLength": 7, "maxLength": 7 },
  { "name": "Japan", "code": "+81", "iso": "JP", "minLength": 10, "maxLength": 10 },
  { "name": "Jordan", "code": "+962", "iso": "JO", "minLength": 9, "maxLength": 9 },
  { "name": "Kazakhstan", "code": "+7", "iso": "KZ", "minLength": 10, "maxLength": 10 },
  { "name": "Kenya", "code": "+254", "iso": "KE", "minLength": 9, "maxLength": 9 },
  { "name": "Kiribati", "code": "+686", "iso": "KI", "minLength": 7, "maxLength": 7 },
  { "name": "Kuwait", "code": "+965", "iso": "KW", "minLength": 8, "maxLength": 8 },
  { "name": "Kyrgyzstan", "code": "+996", "iso": "KG", "minLength": 9, "maxLength": 9 },
  { "name": "Laos", "code": "+856", "iso": "LA", "minLength": 8, "maxLength": 8 },
  { "name": "Latvia", "code": "+371", "iso": "LV", "minLength": 8, "maxLength": 8 },
  { "name": "Lebanon", "code": "+961", "iso": "LB", "minLength": 8, "maxLength": 8 },
  { "name": "Lesotho", "code": "+266", "iso": "LS", "minLength": 8, "maxLength": 8 },
  { "name": "Liberia", "code": "+231", "iso": "LR", "minLength": 7, "maxLength": 7 },
  { "name": "Libya", "code": "+218", "iso": "LY", "minLength": 9, "maxLength": 9 },
  { "name": "Liechtenstein", "code": "+423", "iso": "LI", "minLength": 7, "maxLength": 7 },
  { "name": "Lithuania", "code": "+370", "iso": "LT", "minLength": 8, "maxLength": 8 },
  { "name": "Luxembourg", "code": "+352", "iso": "LU", "minLength": 8, "maxLength": 8 },
  { "name": "Madagascar", "code": "+261", "iso": "MG", "minLength": 9, "maxLength": 9 },
  { "name": "Malawi", "code": "+265", "iso": "MW", "minLength": 9, "maxLength": 9 },
  { "name": "Malaysia", "code": "+60", "iso": "MY", "minLength": 9, "maxLength": 10 },
  { "name": "Maldives", "code": "+960", "iso": "MV", "minLength": 7, "maxLength": 7 },
  { "name": "Mali", "code": "+223", "iso": "ML", "minLength": 8, "maxLength": 8 },
  { "name": "Malta", "code": "+356", "iso": "MT", "minLength": 8, "maxLength": 8 },
  { "name": "Marshall Islands", "code": "+692", "iso": "MH", "minLength": 7, "maxLength": 7 },
  { "name": "Mauritania", "code": "+222", "iso": "MR", "minLength": 8, "maxLength": 8 },
  { "name": "Mauritius", "code": "+230", "iso": "MU", "minLength": 8, "maxLength": 8 },
  { "name": "Mexico", "code": "+52", "iso": "MX", "minLength": 10, "maxLength": 10 },
  { "name": "Micronesia", "code": "+691", "iso": "FM", "minLength": 7, "maxLength": 7 },
  { "name": "Moldova", "code": "+373", "iso": "MD", "minLength": 8, "maxLength": 8 },
  { "name": "Monaco", "code": "+377", "iso": "MC", "minLength": 8, "maxLength": 8 },
  { "name": "Mongolia", "code": "+976", "iso": "MN", "minLength": 8, "maxLength": 8 },
  { "name": "Montenegro", "code": "+382", "iso": "ME", "minLength": 8, "maxLength": 8 },
  { "name": "Morocco", "code": "+212", "iso": "MA", "minLength": 9, "maxLength": 9 },
  { "name": "Mozambique", "code": "+258", "iso": "MZ", "minLength": 9, "maxLength": 9 },
  { "name": "Myanmar", "code": "+95", "iso": "MM", "minLength": 9, "maxLength": 9 },
  { "name": "Namibia", "code": "+264", "iso": "NA", "minLength": 9, "maxLength": 9 },
  { "name": "Nauru", "code": "+674", "iso": "NR", "minLength": 7, "maxLength": 7 },
  { "name": "Nepal", "code": "+977", "iso": "NP", "minLength": 10, "maxLength": 10 },
  { "name": "Netherlands", "code": "+31", "iso": "NL", "minLength": 9, "maxLength": 9 },
  { "name": "New Zealand", "code": "+64", "iso": "NZ", "minLength": 9, "maxLength": 9 },
  { "name": "Nicaragua", "code": "+505", "iso": "NI", "minLength": 8, "maxLength": 8 },
  { "name": "Niger", "code": "+227", "iso": "NE", "minLength": 8, "maxLength": 8 },
  { "name": "Nigeria", "code": "+234", "iso": "NG", "minLength": 10, "maxLength": 10 },
  { "name": "North Korea", "code": "+850", "iso": "KP", "minLength": 8, "maxLength": 8 },
  { "name": "North Macedonia", "code": "+389", "iso": "MK", "minLength": 8, "maxLength": 8 },
  { "name": "Norway", "code": "+47", "iso": "NO", "minLength": 8, "maxLength": 8 },
  { "name": "Oman", "code": "+968", "iso": "OM", "minLength": 8, "maxLength": 8 },
  { "name": "Pakistan", "code": "+92", "iso": "PK", "minLength": 10, "maxLength": 10 },
  { "name": "Palau", "code": "+680", "iso": "PW", "minLength": 7, "maxLength": 7 },
  { "name": "Palestine", "code": "+970", "iso": "PS", "minLength": 9, "maxLength": 9 },
  { "name": "Panama", "code": "+507", "iso": "PA", "minLength": 8, "maxLength": 8 },
  { "name": "Papua New Guinea", "code": "+675", "iso": "PG", "minLength": 8, "maxLength": 8 },
  { "name": "Paraguay", "code": "+595", "iso": "PY", "minLength": 9, "maxLength": 9 },
  { "name": "Peru", "code": "+51", "iso": "PE", "minLength": 9, "maxLength": 9 },
  { "name": "Philippines", "code": "+63", "iso": "PH", "minLength": 10, "maxLength": 10 },
  { "name": "Poland", "code": "+48", "iso": "PL", "minLength": 9, "maxLength": 9 },
  { "name": "Portugal", "code": "+351", "iso": "PT", "minLength": 9, "maxLength": 9 },
  { "name": "Qatar", "code": "+974", "iso": "QA", "minLength": 8, "maxLength": 8 },
  { "name": "Romania", "code": "+40", "iso": "RO", "minLength": 9, "maxLength": 9 },
  { "name": "Russia", "code": "+7", "iso": "RU", "minLength": 10, "maxLength": 10 },
  { "name": "Rwanda", "code": "+250", "iso": "RW", "minLength": 9, "maxLength": 9 },
  { "name": "Saint Kitts and Nevis", "code": "+1-869", "iso": "KN", "minLength": 7, "maxLength": 7 },
  { "name": "Saint Lucia", "code": "+1-758", "iso": "LC", "minLength": 7, "maxLength": 7 },
  { "name": "Saint Vincent and the Grenadines", "code": "+1-784", "iso": "VC", "minLength": 7, "maxLength": 7 },
  { "name": "Samoa", "code": "+685", "iso": "WS", "minLength": 7, "maxLength": 7 },
  { "name": "San Marino", "code": "+378", "iso": "SM", "minLength": 9, "maxLength": 9 },
  { "name": "Sao Tome and Principe", "code": "+239", "iso": "ST", "minLength": 7, "maxLength": 7 },
  { "name": "Saudi Arabia", "code": "+966", "iso": "SA", "minLength": 9, "maxLength": 9 },
  { "name": "Senegal", "code": "+221", "iso": "SN", "minLength": 9, "maxLength": 9 },
  { "name": "Serbia", "code": "+381", "iso": "RS", "minLength": 8, "maxLength": 9 },
  { "name": "Seychelles", "code": "+248", "iso": "SC", "minLength": 7, "maxLength": 7 },
  { "name": "Sierra Leone", "code": "+232", "iso": "SL", "minLength": 8, "maxLength": 8 },
  { "name": "Singapore", "code": "+65", "iso": "SG", "minLength": 8, "maxLength": 8 },
  { "name": "Slovakia", "code": "+421", "iso": "SK", "minLength": 9, "maxLength": 9 },
  { "name": "Slovenia", "code": "+386", "iso": "SI", "minLength": 8, "maxLength": 8 },
  { "name": "Solomon Islands", "code": "+677", "iso": "SB", "minLength": 7, "maxLength": 7 },
  { "name": "Somalia", "code": "+252", "iso": "SO", "minLength": 8, "maxLength": 8 },
  { "name": "South Africa", "code": "+27", "iso": "ZA", "minLength": 9, "maxLength": 9 },
  { "name": "South Korea", "code": "+82", "iso": "KR", "minLength": 9, "maxLength": 9 },
  { "name": "South Sudan", "code": "+211", "iso": "SS", "minLength": 9, "maxLength": 9 },
  { "name": "Spain", "code": "+34", "iso": "ES", "minLength": 9, "maxLength": 9 },
  { "name": "Sri Lanka", "code": "+94", "iso": "LK", "minLength": 9, "maxLength": 9 },
  { "name": "Sudan", "code": "+249", "iso": "SD", "minLength": 9, "maxLength": 9 },
  { "name": "Suriname", "code": "+597", "iso": "SR", "minLength": 7, "maxLength": 7 },
  { "name": "Sweden", "code": "+46", "iso": "SE", "minLength": 9, "maxLength": 9 },
  { "name": "Switzerland", "code": "+41", "iso": "CH", "minLength": 9, "maxLength": 9 },
  { "name": "Syria", "code": "+963", "iso": "SY", "minLength": 9, "maxLength": 9 },
  { "name": "Taiwan", "code": "+886", "iso": "TW", "minLength": 9, "maxLength": 9 },
  { "name": "Tajikistan", "code": "+992", "iso": "TJ", "minLength": 9, "maxLength": 9 },
  { "name": "Tanzania", "code": "+255", "iso": "TZ", "minLength": 9, "maxLength": 9 },
  { "name": "Thailand", "code": "+66", "iso": "TH", "minLength": 9, "maxLength": 9 },
  { "name": "Timor-Leste", "code": "+670", "iso": "TL", "minLength": 7, "maxLength": 7 },
  { "name": "Togo", "code": "+228", "iso": "TG", "minLength": 8, "maxLength": 8 },
  { "name": "Tonga", "code": "+676", "iso": "TO", "minLength": 7, "maxLength": 7 },
  { "name": "Trinidad and Tobago", "code": "+1-868", "iso": "TT", "minLength": 7, "maxLength": 7 },
  { "name": "Tunisia", "code": "+216", "iso": "TN", "minLength": 8, "maxLength": 8 },
  { "name": "Turkey", "code": "+90", "iso": "TR", "minLength": 10, "maxLength": 10 },
  { "name": "Turkmenistan", "code": "+993", "iso": "TM", "minLength": 8, "maxLength": 8 },
  { "name": "Tuvalu", "code": "+688", "iso": "TV", "minLength": 7, "maxLength": 7 },
  { "name": "Uganda", "code": "+256", "iso": "UG", "minLength": 9, "maxLength": 9 },
  { "name": "Ukraine", "code": "+380", "iso": "UA", "minLength": 9, "maxLength": 9 },
  { "name": "United Arab Emirates", "code": "+971", "iso": "AE", "minLength": 9, "maxLength": 9 },
  { "name": "United Kingdom", "code": "+44", "iso": "GB", "minLength": 10, "maxLength": 10 },
  { "name": "United States", "code": "+1", "iso": "US", "minLength": 10, "maxLength": 10 },
  { "name": "Uruguay", "code": "+598", "iso": "UY", "minLength": 8, "maxLength": 8 },
  { "name": "Uzbekistan", "code": "+998", "iso": "UZ", "minLength": 9, "maxLength": 9 },
  { "name": "Vanuatu", "code": "+678", "iso": "VU", "minLength": 7, "maxLength": 7 },
  { "name": "Vatican City", "code": "+379", "iso": "VA", "minLength": 8, "maxLength": 8 },
  { "name": "Venezuela", "code": "+58", "iso": "VE", "minLength": 10, "maxLength": 10 },
  { "name": "Vietnam", "code": "+84", "iso": "VN", "minLength": 9, "maxLength": 9 },
  { "name": "Yemen", "code": "+967", "iso": "YE", "minLength": 9, "maxLength": 9 },
  { "name": "Zambia", "code": "+260", "iso": "ZM", "minLength": 9, "maxLength": 9 },
  { "name": "Zimbabwe", "code": "+263", "iso": "ZW", "minLength": 9, "maxLength": 9 }
];

// ✅ Email validator
export const isValidEmail = (email: string): boolean => {
  const regex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
  return regex.test(email.toLowerCase());
};

// ✅ Phone validator (country-aware)
export const isValidPhone = (phone: string, country: CountryCode): boolean => {
  if (!phone.startsWith(country.code)) return false;
  const numberPart = phone.replace(country.code, "");
  if (!/^\d+$/.test(numberPart)) return false;
  return numberPart.length >= country.minLength && numberPart.length <= country.maxLength;
};

// ✅ Password strength validator
export const isValidPassword = (password: string): boolean => {
  // Minimum 8 chars, 1 uppercase, 1 lowercase, 1 number
  const regex = /^(?=.*[a-z])(?=.*[A-Z])(?=.*\d).{8,}$/;
  return regex.test(password);
};

// ✅ Helper: Get country by code
export const getCountryByCode = (code: string): CountryCode | undefined => {
  return countryCodes.find(c => c.code === code);
};
